variables:
  ARCHIVE_NAME: Blender Export Helper
  ENVIRONMENT: Debug

workflow:
  rules:
    # - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG != null
      variables:
        ENVIRONMENT: Release
        RUNNER: ALPINE

stages:
  - build
  - release

.base_job:
  tags:
    - $RUNNER
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_TAG != null

build_job:
  extends: .base_job
  stage: build
  before_script:
    - chmod +x ./build.sh;
  script:
    - . ./build.sh
  after_script:
    # save id for getting artifacts later
    - echo "JOB_ID=$CI_JOB_ID" >> job.env
    # get version num from inside script
    - echo "TAG=$(cat __init__.py | grep 'version' | cut -d '(' -f2 | cut -d ')' -f1 | tr -d ' ' | tr ',' '.')" >> job.env
  artifacts:
    expire_in: 30 days
    paths:
      - '$ARCHIVE_NAME'
    reports:
      dotenv: job.env

release_job:
  extends: .base_job
  stage: release
  needs:
    - job: build_job
      artifacts: true
  # Use this if we want to switch to tag names being superior to coded version
  # variables:
  #   TAG: '$CI_COMMIT_TAG'
  script:
    - echo "running release_job for $TAG from job $JOB_ID"
  release:
    name: 'Release $TAG'
    description: 'For a list of changes see the [CHANGELOG](https://gitlab.com/setherizor/blender-export-helper/-/blob/main/CHANGELOG.md)'
    tag_name: '$TAG'
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: 'BEH.zip'
          url: 'https://gitlab.com/setherizor/blender-export-helper/-/jobs/$JOB_ID/artifacts/download'
